### ISSUE TITLE
Handle disconnects

### ISSUE THREAD

**Issue by evonzee** [evonzee/StarryPy3k#1]
Have reports of users disconnecting and then unable to rejoin. Either detect this and notify starbound_server so player can reconnect, or drop existing connections when player reconnects.  Needs research to determine cause.

**Comment by evonzee** [comment]
I'm not able to reproduce this, at least with naive disconnect simulations like kill -9 on my client.  Can someone provide logs of a recent user session that wound up jammed like this?

**Comment by miraularka** [comment]
If I recall correctly, this issue seemed to be more prevalent once the Starry playercount reached in the hundreds (100 to 200+).  Not sure if it's some sort of overflow error.

**Comment by evonzee** [comment]
Closing this old issue.  If there are still servers with several hundred users, and they encounter this issue, it can be reopened.
